### PR TITLE
Remove implemented algorithms from suggestions

### PR DESCRIPTION
**Pull request by holmgr**

### CODE REVIEW

**Review by alexsaaf — APPROVED** [review]
Good fix. In the future, maybe the readme should keep a list of implemented algorithms as well?

**Comment by holmgr** [comment]
Yes that would be great, some kind of overview over the implementations and their complexities. Furthermore I think that when we implement an algorithm on the suggestions list it should be removed in the PR. Or what do you think @alexsaaf ?

**Comment by alexsaaf** [comment]
That's probably the best way to do it, to make sure that we don't forget about it. I suppose the PR could include both the removal of the suggestion and the overview of the implementation? @holmgr

**Comment by holmgr** [comment]
@alexsaaf Yes, that would be the best i think.

**Pull request merged**
